CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('Admin', 'Member', 'Guest')),
  status TEXT NOT NULL CHECK (status IN ('Online', 'Active', 'Inactive', 'Invited')),
  joined_date DATE NOT NULL,
  last_active TIMESTAMPTZ NULL,
  sheet JSONB NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_unique_idx ON users ((lower(username)));
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique_idx ON users ((lower(email)));

CREATE TABLE IF NOT EXISTS signup_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  requested_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Pending', 'Approved', 'Rejected')),
  approved_by TEXT NULL,
  approved_at TIMESTAMPTZ NULL,
  rejected_by TEXT NULL,
  rejected_at TIMESTAMPTZ NULL
);

CREATE INDEX IF NOT EXISTS signup_requests_status_idx ON signup_requests (status);
CREATE INDEX IF NOT EXISTS signup_requests_username_lower_idx ON signup_requests ((lower(username)));
CREATE INDEX IF NOT EXISTS signup_requests_email_lower_idx ON signup_requests ((lower(email)));
