import { query } from "@/lib/db";

export type MessageRecord = {
  id: number;
  senderUsername: string;
  recipientUsername: string;
  body: string;
  createdAt: string;
  readAt: string | null;
  chatType: "direct" | "group";
  groupName: string | null;
};

export type ConversationSummary = {
  username: string;
  lastMessageAt: string | null;
  unreadCount: number;
};

type MessageRow = {
  id: number;
  sender_username: string;
  recipient_username: string | null;
  body: string;
  created_at: string;
  read_at: string | null;
  chat_type: "direct" | "group";
  group_name: string | null;
};

type ConversationRow = {
  username: string;
  last_message_at: string | null;
  unread_count: number;
};

let messagesSchemaReadyPromise: Promise<void> | null = null;

function toIsoStringOrNull(value: unknown): string | null {
  if (!value) {
    return null;
  }

  const date = value instanceof Date ? value : new Date(String(value));
  return Number.isNaN(date.getTime()) ? null : date.toISOString();
}

function mapMessageRow(row: MessageRow): MessageRecord {
  return {
    id: row.id,
    senderUsername: row.sender_username,
    recipientUsername: row.recipient_username ?? "",
    body: row.body,
    createdAt: toIsoStringOrNull(row.created_at) ?? new Date().toISOString(),
    readAt: toIsoStringOrNull(row.read_at),
    chatType: row.chat_type,
    groupName: row.group_name,
  };
}

async function ensureMessagesSchema(): Promise<void> {
  if (!messagesSchemaReadyPromise) {
    messagesSchemaReadyPromise = (async () => {
      await query(
        `CREATE TABLE IF NOT EXISTS messages (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          sender_username TEXT NOT NULL,
          recipient_username TEXT NULL,
          body TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          read_at TIMESTAMPTZ NULL,
          chat_type TEXT NOT NULL DEFAULT 'direct' CHECK (chat_type IN ('direct', 'group')),
          group_name TEXT NULL
        )`,
      );

      await query("ALTER TABLE messages ADD COLUMN IF NOT EXISTS chat_type TEXT");
      await query("ALTER TABLE messages ADD COLUMN IF NOT EXISTS group_name TEXT");
      await query("ALTER TABLE messages ALTER COLUMN recipient_username DROP NOT NULL");
      await query("UPDATE messages SET chat_type = 'direct' WHERE chat_type IS NULL");
      await query("ALTER TABLE messages ALTER COLUMN chat_type SET DEFAULT 'direct'");
      await query(
        "ALTER TABLE messages ADD CONSTRAINT messages_chat_type_check CHECK (chat_type IN ('direct', 'group'))",
      ).catch(() => undefined);

      await query(
        "CREATE INDEX IF NOT EXISTS messages_participants_created_idx ON messages (sender_username, recipient_username, created_at)",
      );
      await query(
        "CREATE INDEX IF NOT EXISTS messages_recipient_read_idx ON messages (recipient_username, read_at)",
      );
      await query(
        "CREATE INDEX IF NOT EXISTS messages_group_created_idx ON messages (group_name, created_at)",
      );
    })().catch((error) => {
      messagesSchemaReadyPromise = null;
      throw error;
    });
  }

  await messagesSchemaReadyPromise;
}

export async function getPrimaryAdminUsername(): Promise<string | null> {
  await ensureMessagesSchema();

  const rows = await query<{ username: string }>(
    "SELECT username FROM users WHERE role = 'Admin' ORDER BY id ASC LIMIT 1",
  );

  return rows[0]?.username ?? null;
}

export async function sendMessage(input: {
  senderUsername: string;
  recipientUsername: string;
  body: string;
}): Promise<MessageRecord> {
  await ensureMessagesSchema();

  const senderUsername = input.senderUsername.trim();
  const recipientUsername = input.recipientUsername.trim();
  const body = input.body.trim();

  if (!senderUsername || !recipientUsername || !body) {
    throw new Error("Sender, recipient, and message body are required.");
  }

  if (body.length > 2000) {
    throw new Error("Message is too long.");
  }

  const inserted = await query<MessageRow>(
    `INSERT INTO messages (sender_username, recipient_username, body, chat_type, group_name)
     VALUES ($1, $2, $3, 'direct', NULL)
     RETURNING *`,
    [senderUsername, recipientUsername, body],
  );

  return mapMessageRow(inserted[0]);
}

export async function sendGroupMessage(input: {
  senderUsername: string;
  body: string;
  groupName?: string;
}): Promise<MessageRecord> {
  await ensureMessagesSchema();

  const senderUsername = input.senderUsername.trim();
  const body = input.body.trim();
  const groupName = input.groupName?.trim() || "global";

  if (!senderUsername || !body) {
    throw new Error("Sender and message body are required.");
  }

  if (body.length > 2000) {
    throw new Error("Message is too long.");
  }

  const inserted = await query<MessageRow>(
    `INSERT INTO messages (sender_username, recipient_username, body, chat_type, group_name)
     VALUES ($1, NULL, $2, 'group', $3)
     RETURNING *`,
    [senderUsername, body, groupName],
  );

  return mapMessageRow(inserted[0]);
}

export async function getConversationSummariesForUser(
  username: string,
): Promise<ConversationSummary[]> {
  await ensureMessagesSchema();

  const rows = await query<ConversationRow>(
    `SELECT
      username,
      MAX(created_at) AS last_message_at,
      SUM(unread_increment)::int AS unread_count
     FROM (
       SELECT
         CASE
           WHEN lower(sender_username) = lower($1) THEN recipient_username
           ELSE sender_username
         END AS username,
         created_at,
         CASE
           WHEN lower(recipient_username) = lower($1) AND read_at IS NULL THEN 1
           ELSE 0
         END AS unread_increment
       FROM messages
       WHERE chat_type = 'direct'
         AND recipient_username IS NOT NULL
         AND (lower(sender_username) = lower($1) OR lower(recipient_username) = lower($1))
     ) grouped
     GROUP BY username
     ORDER BY MAX(created_at) DESC`,
    [username],
  );

  return rows.map((row) => ({
    username: row.username,
    lastMessageAt: toIsoStringOrNull(row.last_message_at),
    unreadCount: Number(row.unread_count) || 0,
  }));
}

export async function getConversationSummariesForAdmin(
  adminUsername: string,
): Promise<ConversationSummary[]> {
  return getConversationSummariesForUser(adminUsername);
}

export async function getThreadMessages(input: {
  viewerUsername: string;
  withUsername: string;
}): Promise<MessageRecord[]> {
  await ensureMessagesSchema();

  const viewerUsername = input.viewerUsername.trim();
  const withUsername = input.withUsername.trim();

  if (!viewerUsername || !withUsername) {
    throw new Error("viewerUsername and withUsername are required.");
  }

  const rows = await query<MessageRow>(
    `SELECT *
     FROM messages
     WHERE chat_type = 'direct'
       AND recipient_username IS NOT NULL
       AND (
         lower(sender_username) = lower($1) AND lower(recipient_username) = lower($2)
       ) OR (
         lower(sender_username) = lower($2) AND lower(recipient_username) = lower($1)
       )
     ORDER BY created_at ASC`,
    [viewerUsername, withUsername],
  );

  await query(
    `UPDATE messages
     SET read_at = NOW()
     WHERE lower(sender_username) = lower($1)
       AND lower(recipient_username) = lower($2)
       AND read_at IS NULL`,
    [withUsername, viewerUsername],
  );

  return rows.map(mapMessageRow);
}

export async function getGroupMessages(groupName = "global"): Promise<MessageRecord[]> {
  await ensureMessagesSchema();

  const rows = await query<MessageRow>(
    `SELECT *
     FROM messages
     WHERE chat_type = 'group'
       AND lower(COALESCE(group_name, 'global')) = lower($1)
     ORDER BY created_at ASC`,
    [groupName],
  );

  return rows.map(mapMessageRow);
}

export async function getMessagingParticipants(viewerUsername: string): Promise<string[]> {
  await ensureMessagesSchema();

  const rows = await query<{ username: string }>(
    `SELECT username
     FROM users
     WHERE role IN ('Admin', 'Member')
       AND lower(username) <> lower($1)
     ORDER BY username ASC`,
    [viewerUsername.trim()],
  );

  return rows.map((row) => row.username);
}

export async function getUnreadCountForUser(username: string): Promise<number> {
  await ensureMessagesSchema();

  const rows = await query<{ count: number }>(
    `SELECT COUNT(*)::int AS count
     FROM messages
     WHERE chat_type = 'direct'
       AND lower(recipient_username) = lower($1)
       AND read_at IS NULL`,
    [username.trim()],
  );

  return rows[0]?.count ?? 0;
}

export async function editMessageById(input: {
  messageId: number;
  senderUsername: string;
  body: string;
}): Promise<MessageRecord> {
  await ensureMessagesSchema();

  const senderUsername = input.senderUsername.trim();
  const body = input.body.trim();

  if (!senderUsername || !body) {
    throw new Error("Sender and message body are required.");
  }

  if (body.length > 2000) {
    throw new Error("Message is too long.");
  }

  const rows = await query<MessageRow>(
    `UPDATE messages
     SET body = $3
     WHERE id = $1
       AND lower(sender_username) = lower($2)
     RETURNING *`,
    [input.messageId, senderUsername, body],
  );

  if (!rows[0]) {
    throw new Error("Message not found or cannot be edited.");
  }

  return mapMessageRow(rows[0]);
}

export async function deleteMessageById(input: {
  messageId: number;
  senderUsername: string;
}): Promise<void> {
  await ensureMessagesSchema();

  const senderUsername = input.senderUsername.trim();
  if (!senderUsername) {
    throw new Error("Sender is required.");
  }

  const rows = await query<{ id: number }>(
    `DELETE FROM messages
     WHERE id = $1
       AND lower(sender_username) = lower($2)
     RETURNING id`,
    [input.messageId, senderUsername],
  );

  if (!rows[0]) {
    throw new Error("Message not found or cannot be deleted.");
  }
}
