import { CharacterSheet, createEmptyCharacterSheet } from "@/lib/character-sheet";
import { db, query } from "@/lib/db";

export type UserRecord = {
  id: number;
  username: string;
  password: string;
  email: string;
  role: "Admin" | "Member" | "Guest";
  status: "Online" | "Active" | "Inactive" | "Invited";
  joinedDate: string;
  lastActive: string | null;
  sheet: CharacterSheet;
};

export type PublicUser = Omit<UserRecord, "password">;

export type SignupRequestRecord = {
  id: number;
  username: string;
  email: string;
  password: string;
  message: string;
  requestedAt: string;
  status: "Pending" | "Approved" | "Rejected";
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
};

export type PublicSignupRequest = Omit<SignupRequestRecord, "password">;

type UserRow = {
  id: number;
  username: string;
  password: string;
  email: string;
  role: UserRecord["role"];
  status: UserRecord["status"];
  joined_date: string;
  last_active: string | null;
  sheet: CharacterSheet;
};

type SignupRequestRow = {
  id: number;
  username: string;
  email: string;
  password: string;
  message: string;
  requested_at: string;
  status: SignupRequestRecord["status"];
  approved_by: string | null;
  approved_at: string | null;
  rejected_by: string | null;
  rejected_at: string | null;
};

function toIsoStringOrNull(value: unknown): string | null {
  if (!value) {
    return null;
  }

  const date = value instanceof Date ? value : new Date(String(value));
  return Number.isNaN(date.getTime()) ? null : date.toISOString();
}

function toIsoStringOrNow(value: unknown): string {
  return toIsoStringOrNull(value) ?? new Date().toISOString();
}

function normalizeUsername(value: string): string {
  return value.trim().toLowerCase();
}

function mapUserRow(row: UserRow): UserRecord {
  return {
    id: row.id,
    username: row.username,
    password: row.password,
    email: row.email,
    role: row.role,
    status: row.status,
    joinedDate: row.joined_date,
    lastActive: toIsoStringOrNull(row.last_active),
    sheet: row.sheet,
  };
}

function mapSignupRequestRow(row: SignupRequestRow): SignupRequestRecord {
  return {
    id: row.id,
    username: row.username,
    email: row.email,
    password: row.password,
    message: row.message,
    requestedAt: toIsoStringOrNow(row.requested_at),
    status: row.status,
    approvedBy: row.approved_by ?? undefined,
    approvedAt: toIsoStringOrNull(row.approved_at) ?? undefined,
    rejectedBy: row.rejected_by ?? undefined,
    rejectedAt: toIsoStringOrNull(row.rejected_at) ?? undefined,
  };
}

function toPublicUser(user: UserRecord): PublicUser {
  const publicUser = { ...user } as PublicUser & { password?: string };
  delete publicUser.password;
  return publicUser;
}

function toPublicSignupRequest(request: SignupRequestRecord): PublicSignupRequest {
  const publicRequest = { ...request } as PublicSignupRequest & { password?: string };
  delete publicRequest.password;
  return publicRequest;
}

let schemaReadyPromise: Promise<void> | null = null;

async function ensureSchema(): Promise<void> {
  if (!schemaReadyPromise) {
    schemaReadyPromise = (async () => {
      await query(
        `CREATE TABLE IF NOT EXISTS users (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username TEXT NOT NULL,
          password TEXT NOT NULL,
          email TEXT NOT NULL,
          role TEXT NOT NULL CHECK (role IN ('Admin', 'Member', 'Guest')),
          status TEXT NOT NULL CHECK (status IN ('Online', 'Active', 'Inactive', 'Invited')),
          joined_date DATE NOT NULL,
          last_active TIMESTAMPTZ NULL,
          sheet JSONB NOT NULL
        )`,
      );

      await query(
        "CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_unique_idx ON users ((lower(username)))",
      );
      await query(
        "CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique_idx ON users ((lower(email)))",
      );

      await query(
        `CREATE TABLE IF NOT EXISTS signup_requests (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username TEXT NOT NULL,
          email TEXT NOT NULL,
          password TEXT NOT NULL,
          message TEXT NOT NULL DEFAULT '',
          requested_at TIMESTAMPTZ NOT NULL,
          status TEXT NOT NULL CHECK (status IN ('Pending', 'Approved', 'Rejected')),
          approved_by TEXT NULL,
          approved_at TIMESTAMPTZ NULL,
          rejected_by TEXT NULL,
          rejected_at TIMESTAMPTZ NULL
        )`,
      );

      await query("CREATE INDEX IF NOT EXISTS signup_requests_status_idx ON signup_requests (status)");
      await query(
        "CREATE INDEX IF NOT EXISTS signup_requests_username_lower_idx ON signup_requests ((lower(username)))",
      );
      await query(
        "CREATE INDEX IF NOT EXISTS signup_requests_email_lower_idx ON signup_requests ((lower(email)))",
      );
    })().catch((error) => {
      schemaReadyPromise = null;
      throw error;
    });
  }

  await schemaReadyPromise;
}

export async function getPublicUsers(): Promise<PublicUser[]> {
  await ensureSchema();
  const rows = await query<UserRow>("SELECT * FROM users ORDER BY id ASC");
  return rows.map((row) => toPublicUser(mapUserRow(row)));
}

export async function getPublicSignupRequests(): Promise<PublicSignupRequest[]> {
  await ensureSchema();
  const rows = await query<SignupRequestRow>("SELECT * FROM signup_requests ORDER BY id ASC");
  return rows.map((row) => toPublicSignupRequest(mapSignupRequestRow(row)));
}

export async function findAdminUser(username: string): Promise<UserRecord | undefined> {
  await ensureSchema();
  const rows = await query<UserRow>(
    "SELECT * FROM users WHERE role = 'Admin' AND lower(username) = $1 LIMIT 1",
    [normalizeUsername(username)],
  );

  return rows[0] ? mapUserRow(rows[0]) : undefined;
}

export async function findUserByUsername(username: string): Promise<UserRecord | undefined> {
  await ensureSchema();
  const rows = await query<UserRow>("SELECT * FROM users WHERE lower(username) = $1 LIMIT 1", [
    normalizeUsername(username),
  ]);

  return rows[0] ? mapUserRow(rows[0]) : undefined;
}

export async function findUserByCredentials(
  username: string,
  password: string,
): Promise<UserRecord | undefined> {
  await ensureSchema();
  const rows = await query<UserRow>(
    "SELECT * FROM users WHERE lower(username) = $1 AND password = $2 LIMIT 1",
    [normalizeUsername(username), password],
  );

  return rows[0] ? mapUserRow(rows[0]) : undefined;
}

export async function createSignupRequest(input: {
  username: string;
  email: string;
  password: string;
  message?: string;
}): Promise<PublicSignupRequest> {
  await ensureSchema();
  const normalizedUsername = normalizeUsername(input.username);
  const normalizedEmail = input.email.trim().toLowerCase();

  if (!normalizedUsername || !normalizedEmail || !input.password.trim()) {
    throw new Error("Username, email, and password are required.");
  }

  const usernameTaken = await query<{ exists: boolean }>(
    "SELECT EXISTS(SELECT 1 FROM users WHERE lower(username) = $1) AS exists",
    [normalizedUsername],
  );
  if (usernameTaken[0]?.exists) {
    throw new Error("Username is already taken.");
  }

  const emailTaken = await query<{ exists: boolean }>(
    "SELECT EXISTS(SELECT 1 FROM users WHERE lower(email) = $1) AS exists",
    [normalizedEmail],
  );
  if (emailTaken[0]?.exists) {
    throw new Error("Email is already in use.");
  }

  const pendingExists = await query<{ exists: boolean }>(
    `SELECT EXISTS(
      SELECT 1 FROM signup_requests
      WHERE status = 'Pending' AND (lower(username) = $1 OR lower(email) = $2)
    ) AS exists`,
    [normalizedUsername, normalizedEmail],
  );
  if (pendingExists[0]?.exists) {
    throw new Error("A pending signup request already exists for this username or email.");
  }

  const rows = await query<SignupRequestRow>(
    `INSERT INTO signup_requests (
      username, email, password, message, requested_at, status
    ) VALUES ($1, $2, $3, $4, NOW(), 'Pending') RETURNING *`,
    [input.username.trim(), input.email.trim(), input.password, input.message?.trim() ?? ""],
  );

  return toPublicSignupRequest(mapSignupRequestRow(rows[0]));
}

export async function approveSignupRequest(
  requestId: number,
  reviewerUsername: string,
): Promise<PublicUser> {
  await ensureSchema();
  const client = await db.connect();

  try {
    await client.query("BEGIN");

    const requestRows = await client.query<SignupRequestRow>(
      "SELECT * FROM signup_requests WHERE id = $1 FOR UPDATE",
      [requestId],
    );
    const request = requestRows.rows[0];

    if (!request) {
      throw new Error("Signup request not found.");
    }

    if (request.status !== "Pending") {
      throw new Error("Only pending signup requests can be approved.");
    }

    const normalizedUsername = normalizeUsername(request.username);
    const normalizedEmail = request.email.trim().toLowerCase();

    const usernameConflict = await client.query<{ exists: boolean }>(
      "SELECT EXISTS(SELECT 1 FROM users WHERE lower(username) = $1) AS exists",
      [normalizedUsername],
    );
    if (usernameConflict.rows[0]?.exists) {
      throw new Error("Cannot approve request: username already exists.");
    }

    const emailConflict = await client.query<{ exists: boolean }>(
      "SELECT EXISTS(SELECT 1 FROM users WHERE lower(email) = $1) AS exists",
      [normalizedEmail],
    );
    if (emailConflict.rows[0]?.exists) {
      throw new Error("Cannot approve request: email already exists.");
    }

    const userInsert = await client.query<UserRow>(
      `INSERT INTO users (
        username, password, email, role, status, joined_date, last_active, sheet
      ) VALUES ($1, $2, $3, 'Member', 'Active', CURRENT_DATE, NULL, $4::jsonb)
      RETURNING *`,
      [request.username, request.password, request.email, JSON.stringify(createEmptyCharacterSheet())],
    );

    await client.query(
      `UPDATE signup_requests
       SET status = 'Approved', approved_by = $2, approved_at = NOW(), rejected_by = NULL, rejected_at = NULL
       WHERE id = $1`,
      [requestId, reviewerUsername],
    );

    await client.query("COMMIT");
    return toPublicUser(mapUserRow(userInsert.rows[0]));
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

export async function rejectSignupRequest(
  requestId: number,
  reviewerUsername: string,
): Promise<PublicSignupRequest> {
  await ensureSchema();
  const rows = await query<SignupRequestRow>("SELECT * FROM signup_requests WHERE id = $1 LIMIT 1", [
    requestId,
  ]);
  const request = rows[0];

  if (!request) {
    throw new Error("Signup request not found.");
  }

  if (request.status !== "Pending") {
    throw new Error("Only pending signup requests can be rejected.");
  }

  const updated = await query<SignupRequestRow>(
    `UPDATE signup_requests
     SET status = 'Rejected', rejected_by = $2, rejected_at = NOW(), approved_by = NULL, approved_at = NULL
     WHERE id = $1
     RETURNING *`,
    [requestId, reviewerUsername],
  );

  return toPublicSignupRequest(mapSignupRequestRow(updated[0]));
}

export async function createMemberUser(input: {
  username: string;
  email: string;
  password: string;
}): Promise<PublicUser> {
  await ensureSchema();
  const normalizedUsername = normalizeUsername(input.username);
  const normalizedEmail = input.email.trim().toLowerCase();

  if (!normalizedUsername || !normalizedEmail || !input.password.trim()) {
    throw new Error("Username, email, and password are required.");
  }

  const client = await db.connect();

  try {
    await client.query("BEGIN");

    const usernameTaken = await client.query<{ exists: boolean }>(
      "SELECT EXISTS(SELECT 1 FROM users WHERE lower(username) = $1) AS exists",
      [normalizedUsername],
    );
    if (usernameTaken.rows[0]?.exists) {
      throw new Error("Username is already taken.");
    }

    const emailTaken = await client.query<{ exists: boolean }>(
      "SELECT EXISTS(SELECT 1 FROM users WHERE lower(email) = $1) AS exists",
      [normalizedEmail],
    );
    if (emailTaken.rows[0]?.exists) {
      throw new Error("Email is already in use.");
    }

    const createdUser = await client.query<UserRow>(
      `INSERT INTO users (
        username, password, email, role, status, joined_date, last_active, sheet
      ) VALUES ($1, $2, $3, 'Member', 'Active', CURRENT_DATE, NULL, $4::jsonb)
      RETURNING *`,
      [
        input.username.trim(),
        input.password,
        input.email.trim(),
        JSON.stringify(createEmptyCharacterSheet()),
      ],
    );

    await client.query(
      `UPDATE signup_requests
       SET status = 'Approved', approved_by = 'System', approved_at = NOW(), rejected_by = NULL, rejected_at = NULL
       WHERE status = 'Pending' AND (lower(username) = $1 OR lower(email) = $2)`,
      [normalizedUsername, normalizedEmail],
    );

    await client.query("COMMIT");
    return toPublicUser(mapUserRow(createdUser.rows[0]));
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

export async function deleteUserByUsername(username: string): Promise<PublicUser> {
  await ensureSchema();
  const deleted = await query<UserRow>(
    "DELETE FROM users WHERE lower(username) = $1 AND role <> 'Admin' RETURNING *",
    [normalizeUsername(username)],
  );

  if (deleted[0]) {
    return toPublicUser(mapUserRow(deleted[0]));
  }

  const existing = await query<{ role: UserRecord["role"] }>(
    "SELECT role FROM users WHERE lower(username) = $1 LIMIT 1",
    [normalizeUsername(username)],
  );

  if (!existing[0]) {
    throw new Error("User not found.");
  }

  if (existing[0].role === "Admin") {
    throw new Error("Admin users cannot be deleted.");
  }

  throw new Error("Unable to delete user.");
}

export async function getPublicUserByUsername(username: string): Promise<PublicUser | undefined> {
  await ensureSchema();
  const user = await findUserByUsername(username);
  return user ? toPublicUser(user) : undefined;
}

export async function updateMemberSheetByUsername(
  username: string,
  updates: {
    email?: string;
    status?: "Active" | "Inactive";
    sheet?: CharacterSheet;
  },
): Promise<PublicUser | undefined> {
  await ensureSchema();
  const rows = await query<UserRow>(
    `UPDATE users
     SET
       email = COALESCE($2, email),
       status = COALESCE($3, status),
       sheet = COALESCE($4::jsonb, sheet),
       last_active = NOW()
     WHERE lower(username) = $1
     RETURNING *`,
    [
      normalizeUsername(username),
      updates.email ?? null,
      updates.status ?? null,
      updates.sheet ? JSON.stringify(updates.sheet) : null,
    ],
  );

  if (!rows[0]) {
    return undefined;
  }

  return toPublicUser(mapUserRow(rows[0]));
}

export async function updateAccountCredentials(input: {
  currentUsername: string;
  currentPassword: string;
  newUsername?: string;
  newPassword?: string;
}): Promise<PublicUser> {
  await ensureSchema();

  const currentUsername = input.currentUsername.trim();
  const currentPassword = input.currentPassword;
  const nextUsername = input.newUsername?.trim();
  const nextPassword = input.newPassword;

  if (!currentUsername || !currentPassword) {
    throw new Error("Current username and password are required.");
  }

  if (!nextUsername && !nextPassword) {
    throw new Error("Provide a new username or password.");
  }

  if (nextPassword && nextPassword.trim().length < 6) {
    throw new Error("New password must be at least 6 characters.");
  }

  const verifiedUser = await findUserByCredentials(currentUsername, currentPassword);
  if (!verifiedUser) {
    throw new Error("Current password is incorrect.");
  }

  const shouldUpdateUsername =
    Boolean(nextUsername) && normalizeUsername(nextUsername ?? "") !== normalizeUsername(verifiedUser.username);

  if (shouldUpdateUsername) {
    const usernameTaken = await query<{ exists: boolean }>(
      "SELECT EXISTS(SELECT 1 FROM users WHERE lower(username) = $1 AND id <> $2) AS exists",
      [normalizeUsername(nextUsername ?? ""), verifiedUser.id],
    );

    if (usernameTaken[0]?.exists) {
      throw new Error("Username is already taken.");
    }
  }

  const updatedRows = await query<UserRow>(
    `UPDATE users
     SET
       username = COALESCE($2, username),
       password = COALESCE($3, password),
       last_active = NOW()
     WHERE id = $1
     RETURNING *`,
    [
      verifiedUser.id,
      shouldUpdateUsername ? nextUsername : null,
      nextPassword && nextPassword.trim().length > 0 ? nextPassword : null,
    ],
  );

  if (!updatedRows[0]) {
    throw new Error("Unable to update account.");
  }

  return toPublicUser(mapUserRow(updatedRows[0]));
}
